name: Java CI with JUnit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java project
        run: javac -d out $(find src -name "*.java") $(find test -name "*.java")
        mkdir -p out
        if [ -d "src" ] || [ -d "test" ]; then
        javac -d out $(find src -name "*.java" 2>/dev/null) $(find test -name "*.java" 2>/dev/null)
        else
        echo "No source or test files to compile."
        fi


      - name: Run JUnit tests
        run: |
          java -jar lib/junit-platform-console-standalone-1.10.0.jar \
          --class-path out \
          --scan-class-path
